language: objective-c

osx_image: xcode9
xcode_sdk: iphonesimulator11.0

before_install:
  - chmod +x install_swiftlint.sh
install:
  - ./install_swiftlint.sh

script:
- xcodebuild clean build -workspace TFS.xcworkspace -scheme TFSCore -destination 'platform=iOS Simulator,name=iPad Pro (12.9-inch),OS=11.0'
- xcodebuild clean build -workspace TFS.xcworkspace -scheme TFSARTestApp -destination 'platform=iOS Simulator,name=iPad Pro (12.9-inch),OS=11.0'
- xcodebuild clean build -workspace TFS.xcworkspace -scheme TFSFireworksKit -destination 'platform=iOS Simulator,name=iPad Pro (12.9-inch),OS=11.0'
